### ISSUE TITLE
[feature request] add version parts as keys for file search regex substitution

### ISSUE THREAD

**Issue by biojppm** [TankerHQ/tbump#74]
Thanks for your work!

In my project I have a file where the version is set directly with subfields. Like this:

```c
const Version firmwareVersion = {.major=0, .minor=0, .patch=1, .release=0};
```

So the relevant parts in the config file are:

```toml
[version]
current = "0.0.1.0"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  \.
  (?P<release>\d+)
  '''
[[file]]
src = "src/version.c"
search = '.major={major}, .minor={minor}, .patch={patch}, .release={release}'
```
But then I get an error `KeyError: 'major'`:
```
$ tbump 0.0.1.1 --dry-run
:: Bumping from 0.0.1.0 to 0.0.1.1
Traceback (most recent call last):
  File "c:\python38_64\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38_64\Scripts\tbump.exe\__main__.py", line 7, in <module>
  File "c:\python38_64\lib\site-packages\tbump\main.py", line 198, in main
    run(args)
  File "c:\python38_64\lib\site-packages\tbump\main.py", line 105, in run
    bump(bump_options)
  File "c:\python38_64\lib\site-packages\tbump\main.py", line 156, in bump
    executor = Executor(new_version, file_bumper)
  File "c:\python38_64\lib\site-packages\tbump\executor.py", line 52, in __init__
    file_bumper.get_patches(new_version),
  File "c:\python38_64\lib\site-packages\tbump\file_bumper.py", line 195, in get_patches
    change_requests = self.compute_change_requests()
  File "c:\python38_64\lib\site-packages\tbump\file_bumper.py", line 238, in compute_change_requests
    change_request = self.compute_change_request_for_file(file)
  File "c:\python38_64\lib\site-packages\tbump\file_bumper.py", line 268, in compute_change_request_for_file
    to_search = file.search.format(current_version=re.escape(current_version))
KeyError: 'major'
```

Would it be possible to add the version fields to the dictionary passed to `.format()`?

**Comment by biojppm** [comment]
Just a minor correction: of course, the template on the config file would have to be
```toml
[[file]]
src = "src/version.c"
search = '.major={current_major}, .minor={current_minor}, .patch={current_patch}, .release={current_release}'
```

**Comment by dmerejkowsky** [comment]
> Would it be possible to add the version fields to the dictionary passed to .format()?

That's *almost* how it works.

In fact, you need to tell tbump to _not_ bee looking for `0.0.1.0` when bumping, but for the initialization syntax of the C struct.

Here's how to do it:

```toml
[[file]]
src = "src/version.c"
version_template = ".major={major}, .minor={minor}, .patch={patch}, .release={release}"
search = "const Version firmwareVersion = "
```

**Comment by biojppm** [comment]
Ah, I see. Thanks - it does work!
